// Real organizations worth watching — careers pages stay evergreen even when
// specific listings expire. Lean Canadian / Vancouver-adjacent since the
// owner is in Vancouver, but with global outposts mixed in.

export type Org = {
  id: string;
  name: string;
  blurb: string;
  url: string;
  city?: string;
  tags: ("music" | "fashion" | "film" | "agency" | "media" | "festival" | "hospitality" | "gallery" | "indie" | "publisher" | "tech")[];
  why: string;
};

export const ORGS: Org[] = [
  // -- music / publishing / rights --------------------------------------
  {
    id: "socan",
    name: "SOCAN",
    blurb: "Canadian society of composers, authors, music publishers.",
    url: "https://www.socan.com/about/careers/",
    city: "Toronto / Montreal",
    tags: ["music", "publisher"],
    why: "Real careers in music rights / publishing. Public-mission. The 'cool inside a structured org' move.",
  },
  {
    id: "universal-music-canada",
    name: "Universal Music Canada",
    blurb: "Major label. Marketing, A&R, sync, brand partnerships.",
    url: "https://www.umusic.ca/careers/",
    city: "Toronto",
    tags: ["music"],
    why: "If you want to work with artists at scale and have label proximity.",
  },
  {
    id: "warner-music-canada",
    name: "Warner Music Canada",
    blurb: "Major label, often hiring digital + brand partnership roles.",
    url: "https://careers.wmg.com/",
    city: "Toronto",
    tags: ["music"],
    why: "Same as Universal — different roster, different politics.",
  },
  {
    id: "live-nation-canada",
    name: "Live Nation Canada",
    blurb: "Tours, festivals, venues. Roles all over: marketing, talent, ops.",
    url: "https://www.livenationentertainment.com/careers/",
    city: "Toronto / Vancouver",
    tags: ["music", "festival"],
    why: "Where 'concert' becomes a career path. Loud, fast, real money.",
  },
  {
    id: "feldman-agency",
    name: "The Feldman Agency",
    blurb: "One of Canada's top booking agencies.",
    url: "https://feldman.ca/careers",
    city: "Vancouver / Toronto",
    tags: ["music"],
    why: "Booking, agenting — local + relevant for the agency idea.",
  },
  {
    id: "paquin",
    name: "Paquin Entertainment Group",
    blurb: "Canadian talent + touring agency.",
    url: "https://paquinentertainment.com/contact/",
    city: "Winnipeg / Toronto",
    tags: ["music"],
    why: "Booking / management — small enough to learn the whole stack.",
  },

  // -- film / festivals -------------------------------------------------
  {
    id: "tiff",
    name: "TIFF (Toronto International Film Festival)",
    blurb: "Festival, year-round programs, public lightbox.",
    url: "https://www.tiff.net/careers",
    city: "Toronto",
    tags: ["film", "festival"],
    why: "Programming, marketing, hospitality, ops. Real prestige + real grind.",
  },
  {
    id: "vancouver-international-film-festival",
    name: "VIFF",
    blurb: "Vancouver's film festival + year-round cinema programming.",
    url: "https://viff.org/about/careers/",
    city: "Vancouver",
    tags: ["film", "festival"],
    why: "Local. Often hiring around fall festival.",
  },
  {
    id: "hot-docs",
    name: "Hot Docs",
    blurb: "Documentary festival + cinema in Toronto.",
    url: "https://www.hotdocs.ca/about/careers",
    city: "Toronto",
    tags: ["film", "festival"],
    why: "Doc film world is its own little planet — and a kind one.",
  },
  {
    id: "telefilm-canada",
    name: "Telefilm Canada",
    blurb: "Funds Canadian film + screen industry.",
    url: "https://telefilm.ca/en/careers",
    city: "Montreal",
    tags: ["film"],
    why: "Decide which Canadian movies get made. Civil-service-shaped.",
  },
  {
    id: "cbc",
    name: "CBC / Radio-Canada",
    blurb: "National broadcaster — wild range of creative + production roles.",
    url: "https://cbc.radio-canada.ca/en/working-with-us",
    city: "Toronto / Vancouver / Montreal",
    tags: ["media", "film"],
    why: "Stable, with creative dignity. Many ways in.",
  },
  {
    id: "banff-centre",
    name: "The Banff Centre",
    blurb: "Arts + leadership campus in the Rockies.",
    url: "https://www.banffcentre.ca/careers",
    city: "Banff",
    tags: ["gallery", "festival", "hospitality"],
    why: "Live at the most beautiful job in Canada. Programs in music, indigenous arts, etc.",
  },

  // -- arts / curatorial ------------------------------------------------
  {
    id: "vag",
    name: "Vancouver Art Gallery",
    blurb: "Vancouver's biggest art institution. Curatorial, education, events.",
    url: "https://www.vanartgallery.bc.ca/about-us/employment",
    city: "Vancouver",
    tags: ["gallery"],
    why: "Local. Curation, programming, public events.",
  },
  {
    id: "polygon",
    name: "The Polygon Gallery",
    blurb: "Photography-focused gallery on the North Van waterfront.",
    url: "https://thepolygon.ca/about/careers/",
    city: "North Vancouver",
    tags: ["gallery"],
    why: "Small, smart. Photo + image-culture.",
  },
  {
    id: "power-plant",
    name: "The Power Plant",
    blurb: "Contemporary art gallery in Toronto.",
    url: "https://www.thepowerplant.org/careers",
    city: "Toronto",
    tags: ["gallery"],
    why: "Contemporary art programming, often hires curatorial assistants.",
  },
  {
    id: "moca-toronto",
    name: "MOCA Toronto",
    blurb: "Museum of Contemporary Art, Toronto.",
    url: "https://moca.ca/about-us/careers/",
    city: "Toronto",
    tags: ["gallery"],
    why: "Contemporary, programming-forward, smaller team than VAG.",
  },
  {
    id: "canada-council",
    name: "Canada Council for the Arts",
    blurb: "Federal grant-making body for the arts.",
    url: "https://canadacouncil.ca/about/employment",
    city: "Ottawa",
    tags: ["gallery"],
    why: "Decides who gets funded. Civic, grant officer-shaped.",
  },

  // -- fashion / retail / brand ----------------------------------------
  {
    id: "aritzia",
    name: "Aritzia",
    blurb: "Vancouver-built fashion brand. Creative, brand, digital, retail.",
    url: "https://www.aritzia.com/en/aritzia/careers/careers.html",
    city: "Vancouver",
    tags: ["fashion"],
    why: "Local. Huge creative team. They hire stylists, copywriters, art directors.",
  },
  {
    id: "lululemon",
    name: "Lululemon",
    blurb: "Vancouver athletic-wear giant with a real creative org.",
    url: "https://careers.lululemon.com/",
    city: "Vancouver",
    tags: ["fashion"],
    why: "Local. Big enough that there's room — small enough not to be IBM.",
  },
  {
    id: "ssense",
    name: "SSENSE",
    blurb: "Montreal fashion e-com + media house.",
    url: "https://www.ssense.com/en-us/careers",
    city: "Montreal",
    tags: ["fashion", "media"],
    why: "If high-fashion-meets-tech is your thing. Best of Canadian fashion-adjacent media.",
  },
  {
    id: "herschel",
    name: "Herschel Supply Co.",
    blurb: "Vancouver-born bag brand. Creative, marketing, e-com.",
    url: "https://herschel.com/careers",
    city: "Vancouver",
    tags: ["fashion"],
    why: "Local. Small enough to make a dent.",
  },
  {
    id: "reigning-champ",
    name: "Reigning Champ",
    blurb: "Vancouver elevated basics. Creative + retail.",
    url: "https://www.reigningchamp.com/pages/careers",
    city: "Vancouver",
    tags: ["fashion"],
    why: "Local, small, tasteful. Wynn Bullock-type-energy.",
  },
  {
    id: "mejuri",
    name: "Mejuri",
    blurb: "Toronto fine jewelry + retail.",
    url: "https://mejuri.com/careers",
    city: "Toronto",
    tags: ["fashion"],
    why: "Hot growth-stage brand. Creative, brand, retail leadership.",
  },
  {
    id: "roots",
    name: "Roots Canada",
    blurb: "Heritage Canadian apparel. Creative, brand, retail.",
    url: "https://corporate.roots.com/careers/",
    city: "Toronto",
    tags: ["fashion"],
    why: "Less hype than Aritzia — more institutional, often hiring.",
  },

  // -- agencies / studios ----------------------------------------------
  {
    id: "sid-lee",
    name: "Sid Lee",
    blurb: "Montreal-born global creative agency.",
    url: "https://www.sidlee.com/en/careers",
    city: "Montreal / Toronto / Paris / NY",
    tags: ["agency"],
    why: "If 'creative director at a real agency' is the dream — start here.",
  },
  {
    id: "cossette",
    name: "Cossette",
    blurb: "Canadian creative + media agency.",
    url: "https://cossette.com/careers/",
    city: "Toronto / Montreal / Vancouver",
    tags: ["agency"],
    why: "Big, established, dependable. Good training ground.",
  },
  {
    id: "rethink",
    name: "Rethink",
    blurb: "Independent Canadian agency consistently winning at Cannes Lions.",
    url: "https://rethinkideas.com/careers/",
    city: "Vancouver / Toronto / Montreal",
    tags: ["agency"],
    why: "Local presence in Van + best work in the country. Real.",
  },
  {
    id: "bruce-mau",
    name: "Bruce Mau Design",
    blurb: "Toronto design studio with a philosophical streak.",
    url: "https://brucemaudesign.com/about/",
    city: "Toronto",
    tags: ["agency"],
    why: "Strategy + design at the highest level. Idea-shop.",
  },
  {
    id: "wieden-kennedy",
    name: "Wieden+Kennedy",
    blurb: "Portland-born indie giant. Nike + every cool campaign you've ever seen.",
    url: "https://www.wk.com/work/jobs/",
    city: "Portland / NY / Amsterdam / etc",
    tags: ["agency"],
    why: "The ceiling for traditional creative-agency-as-craft. Apply early; treat as a 5-year dream.",
  },
  {
    id: "mother",
    name: "Mother",
    blurb: "Independent agency with a Mother Design arm.",
    url: "https://motherdesign.com/jobs",
    city: "London / NY / LA",
    tags: ["agency"],
    why: "The brand world's version of cool. Smart, small-ish.",
  },
  {
    id: "anomaly",
    name: "Anomaly",
    blurb: "NY indie agency with Canadian leadership ties.",
    url: "https://anomaly.com/careers",
    city: "NY / Berlin / Shanghai / Toronto",
    tags: ["agency"],
    why: "Brand + product. Smart room.",
  },

  // -- media / publisher / culture -------------------------------------
  {
    id: "the-fader",
    name: "The FADER",
    blurb: "Independent music + youth culture magazine.",
    url: "https://www.thefader.com/contact",
    city: "New York",
    tags: ["media"],
    why: "Editorial + creative roles when they come up — rarer, worth a watch.",
  },
  {
    id: "vice",
    name: "VICE",
    blurb: "Smaller than it was — but still hires editors + producers.",
    url: "https://www.vice.com/en/page/careers",
    city: "NY / Global",
    tags: ["media"],
    why: "If young culture-journalism is the goal.",
  },
  {
    id: "dazed",
    name: "Dazed",
    blurb: "British youth-culture publisher (Dazed, AnOther, etc).",
    url: "https://www.dazeddigital.com/jobs",
    city: "London",
    tags: ["media", "fashion"],
    why: "Fashion / culture editorial at the highest level.",
  },
  {
    id: "ra",
    name: "Resident Advisor (RA)",
    blurb: "Electronic music + nightlife publisher and booking platform.",
    url: "https://ra.co/jobs",
    city: "London / Global remote",
    tags: ["music", "media"],
    why: "If music + community + tech is the lane.",
  },
  {
    id: "boiler-room",
    name: "Boiler Room",
    blurb: "Live music broadcaster.",
    url: "https://boilerroom.tv/jobs",
    city: "London / Global",
    tags: ["music", "media"],
    why: "Cool, scrappy, often hiring producers / community.",
  },
  {
    id: "a24",
    name: "A24",
    blurb: "Indie film + TV studio.",
    url: "https://a24films.com/jobs",
    city: "New York / LA",
    tags: ["film"],
    why: "Tiny job board, big dreams. Set a Google Alert.",
  },

  // -- festivals / hospitality / nightlife ------------------------------
  {
    id: "bass-coast",
    name: "Bass Coast Festival",
    blurb: "BC-rooted electronic + arts festival.",
    url: "https://basscoast.ca/about/jobs",
    city: "Merritt, BC",
    tags: ["festival", "music"],
    why: "Independent festival, art-forward, local.",
  },
  {
    id: "shambhala",
    name: "Shambhala Music Festival",
    blurb: "Long-running BC electronic festival.",
    url: "https://shambhalamusicfestival.com/about/jobs/",
    city: "Salmo, BC",
    tags: ["festival", "music"],
    why: "Family-owned, real. Seasonal hires + year-round.",
  },
  {
    id: "drake-properties",
    name: "Drake Hotel Properties",
    blurb: "Toronto hotel + restaurant + general-store group.",
    url: "https://www.thedrake.ca/about/careers/",
    city: "Toronto",
    tags: ["hospitality"],
    why: "Where 'hospitality' overlaps 'art world'. Hiring across roles.",
  },
  {
    id: "ace-hotel",
    name: "Ace Hotel Group",
    blurb: "The cool-kid hotel chain.",
    url: "https://acehotel.com/careers/",
    city: "Global",
    tags: ["hospitality"],
    why: "Brand + hospitality + music programming. Sister to A24 in cultural-cool.",
  },
  {
    id: "standard-hotels",
    name: "The Standard Hotels",
    blurb: "Hotel group with strong art / nightlife identity.",
    url: "https://www.standardhotels.com/careers",
    city: "NY / LA / London / etc",
    tags: ["hospitality"],
    why: "Programming + brand roles + on-property hospitality jobs.",
  },
];
